freebsd_instance:
  image_family: freebsd-13-1

task:
  env:
    GHC_VER: 9.2.4
    CABAL_VER: 3.6.2.0
    ARTIFACT: "x86_64-portbld-freebsd-ghcup"
    ARCH: 64
    RUNNER_OS: FreeBSD
    DISTRO: na
    GITHUB_WORKSPACE: ${CIRRUS_WORKING_DIR}
    JSON_VERSION: "0.0.7"
    CIRRUS_CLONE_SUBMODULES: true
    AWS_ACCESS_KEY_ID: ENCRYPTED[3e99c4ac040871f213abd616ec66952d954dc289cdd97772f88e58a74d08a2250133437780fe98b7aedf7ef1fb32f5eb]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[5910cfd77a922ff7fc06eeb6a6b9f79d4867863e541f06eb2c4cfecae0613650e3e0588373fa8d9249d295d76cf9cb3b]
  install_script: pkg install -y ghc hs-cabal-install git bash misc/compat10x misc/compat11x misc/compat12x gmake
  script:
    - bash .github/scripts/build.sh
    - bash .github/scripts/test.sh
  binaries_artifacts:
    path: "out/x86_64-portbld-freebsd-ghcup-*"
