variables:
  GIT_SSL_NO_VERIFY: "1"

  # Commit of ghc/ci-images repository from which to pull Docker images
  DOCKER_REV: cefaee3c742af193e0f7783f87edb0d35374515c

############################################################
# CI Step
############################################################

.debian:
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-deb9:$DOCKER_REV"
  tags:
    - x86_64-linux

.darwin:
  tags:
    - x86_64-darwin

.test_ghcup_version:
  script:
    - ./.gitlab/script/ghcup_version.sh
  variables:
    JSON_VERSION: "0.0.1"

.test_ghcup_version:linux:
  extends:
    - .test_ghcup_version
    - .debian
  before_script:
    - ./.gitlab/before_script/linux/install_deps.sh
  variables:
    OS: "LINUX"

.test_ghcup_version:darwin:
  extends:
    - .test_ghcup_version
    - .darwin
  before_script:
    - ./.gitlab/before_script/darwin/install_deps.sh
  variables:
    OS: "DARWIN"
  after_script:
    - BUILD_DIR=$CI_PROJECT_DIR
    - echo "Cleaning $BUILD_DIR"
    - cd $HOME
    - rm -Rf "$BUILD_DIR"/*
    - exit 0



######## linux ########

test:linux:recommended:
  extends: .test_ghcup_version:linux
  variables:
    GHC_VERSION: "recommended"

test:linux:latest:
  extends: .test_ghcup_version:linux
  variables:
    GHC_VERSION: "latest"
  allow_failure: true


######## darwin ########

test:mac:recommended:
  extends: .test_ghcup_version:darwin
  variables:
    GHC_VERSION: "recommended"

test:mac:latest:
  extends: .test_ghcup_version:darwin
  variables:
    GHC_VERSION: "latest"
  allow_failure: true

