jobs:
  include:
    - os: osx
      osx_image: xcode8
      language: generic
      env: ARTIFACT=x86_64-apple-darwin-10.11-ghcup

    - os: osx
      osx_image: xcode10.1
      language: generic
      env: ARTIFACT=x86_64-apple-darwin-10.13-ghcup

    - os: osx
      osx_image: xcode11.3
      language: generic
      env: ARTIFACT=x86_64-apple-darwin-10.14-ghcup

  allow_failures:
    - os: osx
      osx_image: xcode8
      language: generic
      env: ARTIFACT=x86_64-apple-darwin-10.11-ghcup


script: ".travis/build.sh"

deploy:
  provider: releases
  api_key:
    secure: GQESg4TcYf3PQJRRaZV/kWS0hsF+OFnH2+EcwpgnIcfx4+aogMyprdh745KtBXe1FlFN1luKHksFjqceqhcg/xcNyeCJiSnLWMn4D/i4WUperEHseRBi5yZZCB1AvOjIlHrE4DS3a8pyEm1GV3G7CKY5Fu8jBjof2SnyENfd7fofhjtNHWmeFS+jBn8HRDf1YaSRYxzTw6uHLrPLsybfgQZVl7babMu/38Ghin0f5pz5OlNokzDxaubIYQHOZ7st7YndHJtBWWql/KualBWbMILy88dUVQBnbqQLP2P8d1ME8ILUjJVqz33HiRU0JzlEJyWfbvEjcJ6iD8M6n4nXTaxfu3i2UhhGsQ6SSBNKssMP4tji8nkNpMqG59wLQ/zhcetEm71fKkgJNrIMNllkqlWSo5K74IqqP9kiLg/qm8ipOJjui0gPk8tZXKcV+ztX1d1OVCapoLfiDM5l/0LLQXaTOXOV1x3e5LLQ/w2doNiH3eh5CV4II9dRu7owpaiiMBHMssmT0pH99jEeF6giHLKtt3y7l2GWoRLPdhsZZ54gxsaBxZt9GuypmkbNcr97CEnAVaWij5v0CF3w4rAWqy/tAxQpIDJOIOQBgmwG5WrBAKyKrFvEpBL5a8BPcRWJDvqKC83QeWpvPrEVdgJevC6ZN1MKzrb2SiPOwC2Kerc=
  file: $ARTIFACT
  on:
    repo: haskell/ghcup-hs
    tags: true
  skip_cleanup: true
  draft: true

