site_name: GHCup
site_url: https://www.haskell.org/ghcup
site_description: GHCup is an installer for the general purpose language Haskell.
site_author: GHCup Team
site_favicon: haskell_logo.png

repo_url: https://gitlab.haskell.org/haskell/ghcup-hs

theme:
    name: mkdocs
    locale: en
    custom_dir: docs/overrides

nav:
  - Home: index.md
  - "Getting started": install.md
  - "First steps": steps.md
  - "User Guide": guide.md
  - "Developer Guide": dev.md
  - About: about.md

extra_css:
    - css/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - attr_list
    - def_list
    - meta

