name: Optparse Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ghcup-optparse-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: 9.2.8
          cabal-version: 3.10.1.0
      - run:
          cabal test ghcup-optparse-test
