name: Shellcheck

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    env:
      JSON_VERSION: "0.0.7"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Run shellcheck
        uses: docker://koalaman/shellcheck-alpine
        with:
          args: shellcheck scripts/bootstrap/bootstrap-haskell
